# Generated by Django 4.2 on 2024-02-15 05:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('seats', '0003_arrangement_columns_arrangement_rows_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arrangement',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='arrangements', to=settings.AUTH_USER_MODEL, verbose_name='Классный руководитель'),
        ),
    ]
