# Generated by Django 4.2 on 2024-02-15 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seats', '0004_alter_arrangement_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arrangement',
            name='teacher',
        ),
    ]
